<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />

	<title><?php echo SITE_NAME; ?> > <?php echo fetchTranslation('admin', 'ucfirst'); ?> > <?php echo fetchTranslation('orphaned_files', 'ucfirst'); ?></title>
	
    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
    	<script type="text/javascript">
    		var SITE_PHRASES = new Array();
			<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
				SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
			<?php endforeach; ?>
    	</script>
    <?php endif; ?>		
		    		   	    
	<script type="text/javascript">
		var DATATABLE				= null;
		var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
		var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_ADMIN_PRELOADER_IMAGE_PATH; ?>';
		var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
		var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
		var SITE_NAME				= '<?php echo SITE_NAME; ?>';			
		var CURRENT_USER			= new Array();	
				
		<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
			CURRENT_USER['<?php echo $key; ?>'] = '<?php echo $value; ?>';
		<?php endforeach; ?>
	</script>	

	<!-- Bootstrap -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/bootstrap.min.css">
	<!-- Bootstrap responsive -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/bootstrap-responsive.min.css">
	<!-- jQuery UI -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/jquery-ui/smoothness/jquery-ui.css">
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/jquery-ui/smoothness/jquery.ui.theme.css">
	<!-- dataTables -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/datatable/TableTools.css">
	<!-- chosen -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/chosen/chosen.css">
	<!-- Theme CSS -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/style.css">
	<!-- Color CSS -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/themes.css">

	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>
	<!-- jQuery -->
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>
	<!-- Bootstrap -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/bootstrap.min.js"></script>	
	
	<!-- Nice Scroll -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/nicescroll/jquery.nicescroll.min.js"></script>
	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
	<!-- imagesLoaded -->
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/imagesLoaded/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/img-preload.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/jquery.blockUI.defaults.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>	
	<!-- jQuery UI -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.core.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.sortable.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.datepicker.min.js"></script>
	<!-- slimScroll -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<!-- Bootbox -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/bootbox/jquery.bootbox.js"></script>
	<!-- dataTables -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/TableTools.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/ColReorderWithResize.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/ColVis.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.columnFilter.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.grouping.js"></script>
	<!-- Chosen -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/chosen/chosen.jquery.min.js"></script>

	<!-- Theme framework -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/eakroko.min.js"></script>
	<!-- Theme scripts -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/application.js"></script>
	<!-- Just for demonstration -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/demonstration.min.js"></script>

	<!--[if lte IE 9]>
		<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->
	
	<!-- Favicon -->
	<link rel="shortcut icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/favicon.ico" />
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/apple-touch-icon-precomposed.png" />

	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/custom.css?<?php echo rand(); ?>">
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/custom.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/jquery.observor.js?<?php echo rand(); ?>"></script>	
</head>

	<?php if( strlen( trim( $_COOKIE['adminTemplateColor'] ) ) ): ?>
		<body class="theme-<?php echo $_COOKIE['adminTemplateColor']; ?>" data-theme="theme-<?php echo $_COOKIE['adminTemplateColor']; ?>">
	<?php else: ?>
		<body>
	<?php endif; ?>
	
	<?php echo $this->partial('partials/blockui.phtml'); ?>
	
	<div id="navigation">
		<div class="container-fluid">
			<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin" id="brand"><?php echo SITE_NAME; ?></a>
			<a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title="Toggle navigation"><i class="icon-reorder"></i></a>
			<ul class="main-nav">
				<li>
					<a href="#" data-toggle="dropdown" class="dropdown-toggle">
						<span><?php echo ucfirst( fetchTranslation('settings') ); ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin"><?php echo ucfirst( fetchTranslation('site') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/phrases"><?php echo ucfirst( fetchTranslation('phrases') ); ?></a>
						</li>						
					</ul>
				</li>
				<li>
					<a href="#" data-toggle="dropdown" class='dropdown-toggle'>
						<span><?php echo fetchTranslation('users', 'ucfirst'); ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/users"><?php echo ucfirst( fetchTranslation('all') ); ?></a>
						</li>
					</ul>
				</li>
				<li class="active">
					<a href="#" data-toggle="dropdown" class='dropdown-toggle'>
						<span><?php echo ucfirst( fetchTranslation('files') ); ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/files"><?php echo ucfirst( fetchTranslation('all') ); ?></a>
						</li>
						
						<li class="active">
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/files-orphaned"><?php echo fetchTranslation('orphaned', 'ucwords'); ?></a>
						</li>						
					</ul>
				</li>
			</ul>
			<div class="user">
				<ul class="icon-nav">					
					<li class="dropdown colo">
						<a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-tint"></i></a>
						<ul class="dropdown-menu pull-right theme-colors">
							<li class="subtitle">
								<?php echo fetchTranslation('template_color'); ?>
							</li>
							<li>
								<span class='red'></span>
								<span class='orange'></span>
								<span class='green'></span>
								<span class="brown"></span>
								<span class="blue"></span>
								<span class='lime'></span>
								<span class="teal"></span>
								<span class="purple"></span>
								<span class="pink"></span>
								<span class="magenta"></span>
								<span class="grey"></span>
								<span class="darkblue"></span>
								<span class="lightred"></span>
								<span class="lightgrey"></span>
								<span class="satblue"></span>
								<span class="satgreen"></span>
							</li>
						</ul>
					</li>
					<li class="dropdown language-select">						 				
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<?php if( $_SESSION['user']['site_language'] == 1 ): ?>	
								<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/us.gif" alt="">												
								<span>English (U.S.)</span>
							<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>
								<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/de.gif" alt="">
								<span>Deutsch</span>
							<?php endif; ?>
						</a>
						<ul class="dropdown-menu pull-right">
							<li>
								<a href="#" id="dropdown-langChange" data-langid="<?php if( $_SESSION['user']['site_language'] == 1 ): ?>2<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>1<?php endif;?>">
									<?php if( $_SESSION['user']['site_language'] == 1 ): ?>	
										<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/de.gif" alt="">					
										<span>Deutsch</span>
									<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>
										<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/us.gif" alt="">
										<span>English (U.S.)</span>
									<?php endif; ?>								
								</a>
							</li>
						</ul>
					</li>
				</ul>
				<div class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $_SESSION['user']['email']; ?> <img class="adminAvatarThumb" src="<?php echo $_SESSION['user']['avatar_url']; ?>" alt=""></a>
					<ul class="dropdown-menu pull-right">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/profile"><?php echo ucfirst( fetchTranslation('account_settings') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/logout"><?php echo fetchTranslation('logoff'); ?></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid" id="content">
		<div id="left">
			<div class="subnav subnav-hidden">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( fetchTranslation('settings') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/settings"><?php echo ucfirst( fetchTranslation('site') ); ?></a>
					</li>
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/phrases"><?php echo ucfirst( fetchTranslation('phrases') ); ?></a>
					</li>
				</ul>
			</div>
			
			<div class="subnav subnav-hidden">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( fetchTranslation('users') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/users"><?php echo ucfirst( fetchTranslation('all') ); ?></a>
					</li>
				</ul>
			</div>
			
			<div class="subnav">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( fetchTranslation('files') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/files"><?php echo ucfirst( fetchTranslation('all') ); ?></a>
					</li>
					
					<li class="active">
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/files-orphaned"><?php echo fetchTranslation('orphaned', 'ucwords'); ?></a>
					</li>					
				</ul>
			</div>			
		</div>
		<div id="main">
			<div class="container-fluid">
				<div class="page-header">
					<div class="pull-left">
						<h1><?php echo fetchTranslation('orphaned_files', 'ucwords'); ?></h1>
					</div>
					<div class="pull-right">
						<ul class="stats">
							<li class='lightred'>
								<i class="icon-calendar"></i>
								<div class="details">
									<span class="big"></span>
									<span></span>
								</div>
							</li>
						</ul>
					</div>
				</div>
				<div class="breadcrumbs">
					<ul>
						<li>
							<a target="_blank" href="<?php echo PROTOCOL_RELATIVE_URL; ?>"><?php echo SITE_NAME; ?></a>
							<i class="icon-angle-right"></i>
						</li>					
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin"><?php echo fetchTranslation('admin', 'ucfirst'); ?></a>
							<i class="icon-angle-right"></i>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/files"><?php echo fetchTranslation('files', 'ucfirst'); ?></a>
						</li>
					</ul>
					<div class="close-bread">
						<a href="#"><i class="icon-remove"></i></a>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="span12">
						<div class="box box-color box-bordered">
							<div class="box-title">
								<h3><i class="icon-th-list"></i> <?php echo fetchTranslation('orphaned_files', 'ucwords'); ?></h3>
							</div>
							<div class="box-content nopadding">
								<!-- table id="tblFiles" class="table table-hover table-nomargin dataTable table-bordered"-->
								<table id="tblFiles" class="table table-hover table-nomargin table-bordered">
									<thead>
										<tr>
											<th>File</th>
											<th>Path</th>										
											<th class="with-checkbox">
												Edit
												<div style="float: right;">
													<input type="checkbox" name="cbCheckAllFiles" class="cbCheckAllFiles">
												</div>													
											</th>
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<script type="text/javascript">
		$(document).ready(function() {			 
			/* create an array with the values of all the checkboxes in a column */
			$.fn.dataTableExt.afnSortData['dom-checkbox'] = function  ( oSettings, iColumn ) {
			    return $.map( oSettings.oApi._fnGetTrNodes(oSettings), function (tr, i) {
			        return $('td:eq('+iColumn+') input', tr).prop('checked') ? '1' : '0';
			    } );
			}

			DATATABLE = $('#tblFiles')
	        .bind('sort', function () { 
	        	$('#tblFiles_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            }); 
			})
	        .bind('filter', function () { 
	        	$('#tblFiles_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            });
			})
	        .bind('page', function () { 
	        	$('#tblFiles_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            });
			})
	        .dataTable({
		        'aoColumns': [null,
		                      null,	    
							  // START:	options column                  
		                      {	'mDataProp': null,
								'sClass': 'with-checkbox',
								'sDefaultContent': '<a data-id="__ID__" href="#" class="btn adminFileView" rel="tooltip" title="View"><i class="icon-search"></i></a>&nbsp;<a data-id="__ID__" href="#" class="btn adminFileEdit" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>&nbsp;<a data-id="__ID__" href="#" class="btn adminFileDelete" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>&nbsp;<div style="float: right;"><input type="checkbox" class="cbDataTables" value="1"></div>',
								'sWidth': '11%',
								'mRender': function ( data, type, full ) {
									var newData = str_replace('__ID__', full[8], data); 										
									return newData;
								},
								'bSearchable': false								
							  }
							  // END:	options column							  		                      
				],
				aoColumnDefs: [{bSortable: false,
								aTargets: [ -1 ]								
				}],							
				'bProcessing': false,
				'bServerSide': true,
				'sAjaxSource': BASEURL + '/admin/ajax',
				'sServerMethod': 'POST',
			    'fnServerParams': function ( sSource, aoData, fnCallback, oSettings ) {
			    	sSource.push( { 'name': 'method', 'value': 'dataTablesFilesOrphaned' } );
				},
			    'fnServerData': function ( sSource, aoData, fnCallback, oSettings ) {
					oSettings.jqXHR = $.ajax({
						'dataType': 'json',
						'type': 'POST',
						'url': sSource,
						'data': aoData,
						'complete': function() {
							$('#tblFiles_wrapper').unblock();
						},
						'success': fnCallback	
			        });
				}											
			});

		    $.imgpreload([BASEURL + '/images/preloader/285-black-128x128.gif'], {
				each: function() {
    		        // this = dom image object
    		        // check for success with: $(this).data('loaded')
    		        // callback executes on every image load
				},
				all: function() {
    		        // this = array of dom image objects
    		        // check for success with: $(this[i]).data('loaded')
    		        // callback executes when all images are loaded
				}
			});		    
		});	
	</script>	
	
	<?php echo $this->partial('partials/img-preload.phtml'); ?>	
</body>
</html>