<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title><?php echo SITE_NAME; ?></title>
        <meta name = "viewport" content = "width = 320px">
        <script type="text/javascript" src="<?php echo BASEURL; ?>/js/jquery-1.8.3.min.js"></script>
        <script type="text/javascript" src="<?php echo BASEURL; ?>/js/jquery.blockUI.js"></script>
</head>
<body>

    <div id="wrap" class="grid-all group">

<div style="width: 100%; margin: 0 auto;">
    <a href="<?php echo BASEURL; ?>">
        <img style="margin-left: 0em; margin-top: 1.0em;" src="<?php echo BASEURL; ?>/static/images/headerWithTitle.png"><br/>
    </a>
    
    <div>
		<?php echo $this->message ?>
	</div>
				
	<?php if( strlen( $this->trace ) ): ?>
		<div style="margin-bottom: 5px;">Exception:</div>
		<div>	
			<textarea rows="50" cols="100"><?php echo $this->trace ?></textarea>
		</div>		
	<?php endif; ?>
	
</div>

    </div>
		<script type="text/javascript">
		    $(document).ready(function() {
		    	$.unblockUI();
		    });		    				    
		</script>

		<!-- START:		blockUI -->
		<div style="display: block" class="blockUI"></div>
		<div style="z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(255, 255, 255); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
		<div style="z-index: 1011; display: block; position: fixed" class="blockUI blockMsg blockPage"></div>		
		<!-- END:		blockUI -->
		
	</body>
</html>