<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $_SESSION['user']['locale']; ?>" class="hl-<?php echo $_SESSION['user']['locale']; ?> not-logged-in ">
<head>
    <title><?php echo $_SESSION['site']['phrases']['login']; ?> &mdash; <?php echo SITE_NAME; ?></title>
    
 	<?php
		if( SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;
		} else {
 			$currentTheme = SITE_DEFAULT_TEMPLATE;
 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
		}  
	?>
	
	<?php $siteThemes = $GLOBALS['SITE_THEMES']; ?>    	 
			
	<?php if( !empty( $siteThemes ) ): ?>
		
		<?php 		
			if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
				if( !array_key_exists( $currentTheme, $siteThemes ) ) {
					$currentTheme = SITE_DEFAULT_TEMPLATE;
					setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
				}
			}
		?>
					
		<script type="text/javascript">	
			var SITE_THEMES = new Array();
			<?php foreach( $siteThemes AS $key => $value ): ?>
				SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';	
			<?php endforeach; ?>
		</script>
		<?php else: ?>
		<script type="text/javascript">		
			var SITE_THEMES = new Array();
		</script>			
	<?php endif; ?>
    
	<script type="text/javascript">
		var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
		var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
		var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
		var IS_NORMALIZED			= false;
		var SITE_NAME				= '<?php echo SITE_NAME; ?>';
		var DEMO_MODE				= <?php echo (int)SITE_DEMO_MODE; ?>;
	</script>	    

    <meta charset="UTF-8" />    
    <meta name="robots" content="noimageindex" />
    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon.ico" />
    <meta id="viewport" name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/themeswitcher.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.jrumble.1.3.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bluebar.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/webtoolkit.sha1.js"></script>
	
	<script type="text/javascript">
		__DEV__ = false;
		window._jscalls = [];
		var LOGIN_ERROR = '<?php echo (int)$_SESSION['user']['login_error']; ?>';
	</script>

	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/polyfills-build/polyfill_modern.js"></script>
	<script data-main="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/modules-build/main.js" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/require.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/strings/strings_en.js"></script>

    <link rel="stylesheet" type="text/css" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/dialog-main.css">
    <link rel="stylesheet" type="text/css" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/login.css"/>
    <!--[if lt IE 9]>
    <style>
        .dialog-outer {
            min-height: 0;
        }
    </style>
    <![endif]-->

	<?php if( $currentTheme != 'instagram'): ?>
		<?php if( !array_key_exists( $currentTheme, $siteThemes ) ): ?>
			<link rel="stylesheet" id="theme-url" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/<?php echo $currentTheme; ?>/jquery-ui.css" type="text/css" media="screen" />
			<?php else: ?>
			<link rel="stylesheet" id="normalizeCss" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/normalize.css" type="text/css" />
			<link rel="stylesheet" id="theme-url" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery-ui/themes/<?php echo $currentTheme; ?>/jquery-ui.css" type="text/css" media="screen" />		
		<?php endif; ?>		
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/fg.menu.css" type="text/css" />
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/fg.menu.js"></script>
		
	<?php else: ?>
		<link rel="stylesheet" id="theme-url" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery-ui/themes/cobalt/jquery-ui.css" type="text/css" media="screen" />
	<?php endif; ?>
			
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery.selectBoxIt.css" type="text/css" />			
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/font-awesome.min.css">	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.selectBoxIt.min.js"></script>
	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.pnotify.min.js"></script>
	<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery.pnotify.default.css" media="all" rel="stylesheet" type="text/css" />
	<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery.pnotify.default.icons.css" media="all" rel="stylesheet" type="text/css" />
	<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/public/jquery.pnotify.icons.css" media="all" rel="stylesheet" type="text/css" />	
	    
</head>

<body class="p-dialog oauth-login">
	<!-- START:	blockUI -->
		<div style="display: block" class="blockUI"></div>
		<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(255, 255, 255); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
		<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><img src="<?php echo PROTOCOL_RELATIVE_URL.'/'.SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>"></div>		
	<!-- END:	blockUI -->	
		
	<div class="root">
		<section class="dialog-outer">
		    <div class="instagram dialog" id="dialog" <?php if( $currentTheme != 'instagram' ): ?> style="display: none;" <?php endif; ?>>		
		        <header>
		            <h1 class="logo"><?php echo SITE_NAME; ?></h1>
		
		        </header>

		        <div class="dialog-main" id="dialog-main">		
		        
		        	<?php if( $_SESSION['user']['login_error'] == 1 ): ?>
						<div class="alerts" id="alerts">
							<p class="alert-red">Please enter a correct username and password. Note that both fields are case-sensitive.</p>
						</div>
					<?php endif; ?>
		
		            <form method="POST" name="login-form" id="login-form" onsubmit="document.forms['login-form']['password'].value = SHA1(document.forms['login-form']['password'].value);" class="adjacent" action="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/login/?<?php echo PROTOCOL_RELATIVE_URL; ?>/activity">
		                <div id="loginInput">
			                <input type="hidden" name="csrfmiddlewaretoken" value="a426e376ee6a1fc339701a7dd487e0b7"/>
			                
			                <p id="loginUsernameHolder">
			                	<label for="id_username"><?php echo $_SESSION['site']['phrases']['username']; ?>:</label> 
			                	<input name="username" maxlength="30" autocapitalize="off" autocorrect="off" type="text" id="id_username" />
			                </p>
							<p id="loginPasswordHolder">
								<label for="id_password"><?php echo $_SESSION['site']['phrases']['password']; ?>:</label> 
								<input autocapitalize="off" autocorrect="off" type="password" name="password" id="id_password" />
							</p>
							
						</div>
						
	                    <?php if( (int)SITE_ALLOW_SIGNUP == 1 ): ?>
	                    	<span>
								<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/register/"><?php echo $_SESSION['site']['phrases']['register']; ?></a>
							</span>		                    
	                    <?php endif; ?>						
		                <p class="form-actions">
		                    <a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/password/reset/"><?php echo $_SESSION['site']['phrases']['forgot_password']; ?></a>
		                    <input type="submit" class="button-green" value="Log in" id="btnLogin" />
		                </p>		                
		            </form>
		        </div>	
		        
				<div style="background: url('images/branding/glyph.png') no-repeat scroll 0 0 transparent; bottom: 0; content: ''; display: block; height: 44px; left: 50%; margin: 0 0 -84px -22px; padding-bottom: 20px; position: absolute; width: 44px;"></div>		        	
			</div>
			
			<div class="jquery-ui" id="dialog-form" <?php if( $currentTheme == 'instagram' ): ?> style="min-height: 35px; display: none;" <?php endif; ?>>				
				<div class="ui-widget" id="alerts" style="display: none;">
					<div style="padding: 7px; max-height: 35px;" class="ui-state-error ui-corner-all">
						<p>
							<span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
							<strong>ERROR:</strong> Authentication Failure.
						</p>
					</div>
				</div>				
				
				<form method="POST" name="login-form" id="login-form" action="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/login/?next=<?php echo PROTOCOL_RELATIVE_URL; ?>/activity">
					<table style="width: 100%;">
						<tr>
							<td>
								<label for="username"><?php echo $_SESSION['site']['phrases']['username']; ?></label>							
							</td>
							<td>
								<input autocomplete="off" value="" style="width: 100%;" type="text" name="username" id="username" class="text ui-widget-content ui-corner-all" required />							
							</td>
						</tr>
						<tr>
							<td>
								<label for="password"><?php echo $_SESSION['site']['phrases']['password']; ?></label>							
							</td>
							<td>
								<input autocomplete="off" value="" style="width: 100%;" type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" required />							
							</td>												
						</tr>
					</table>					
				</form>
				
				<div>
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/password/reset/"><?php echo $_SESSION['site']['phrases']['forgot_password']; ?></a>
					<?php if( (int)SITE_ALLOW_SIGNUP == 1 ): ?>
						<br>				
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/accounts/register/"><?php echo $_SESSION['site']['phrases']['register']; ?></a>					
					<?php endif; ?>															
				</div>															
			</div>										
								
		</section>
				
		<script type="text/javascript">
		    $(document).ready(function() {
		    	$.pnotify.defaults.styling		= 'jqueryui';
		    	$.pnotify.defaults.history		= false;
		    	$.pnotify.defaults.maxonscreen 	= '1';			    
		    	$.blockUI.defaults.baseZ		= 1007;

		    	if( parseInt( DEMO_MODE ) == 1 ) {
					$.pnotify({
						title: 'Demo Login',
						text: 'Username:  Demo<br>Password:  password',
						type: 'success',
						icon: 'picon picon-dialog-information',
						hide: false,
						width: '400px'
					});

			    	$('#buyNow').click(function(event) {
				    	event.stopPropagation();
				    	$.blockUI({ message: '<img src="'+BASEURL + '/images/preloader/cart/ig_blue_128x128.gif" border="0">' });
				    				    	
						$.pnotify_remove_all();												
						$.pnotify({
							title: 'Redirecting to PayPal',
							text: 'Hold tight. We are redirecting you to PayPal...',
							type: 'success',
							icon: 'picon picon-flag-green',
							hide: false,
							width: '400px'
						});
			    	});									    	
		    	}		    				    	
		    				    
			    if( CURRENT_THEME != 'instagram' ) {
			    	$('th, tr:last-child td').css('border-bottom', '0');
			    	$('th, td').css('border-bottom', '0');			    	 
				    				          				    					    							    
					$('#dialog-form').dialog({
						closeOnEscape: false,
						autoOpen: true,
						draggable: false,
		    		 	minHeight: 200,
		    		 	minWidth: 550,
		    		 	modal: false,
		    		 	resizable: false,
		    		 	title: '<span class="icon-key"></span> Logon to ' + SITE_NAME,
		    		 	buttons: {
		    		 		'<?php echo $_SESSION['site']['phrases']['login']; ?>' : function() {
								if( strlen( trim( $('#username').val() ) ) && strlen( trim( $('#password').val() ) ) ) {
									$('#username').removeClass('ui-state-error');
									$('#password').removeClass('ui-state-error');

									var username = $('#username').val();
									var password = sha1( $('#password').val() );

									$('.ui-dialog').css('z-index', '1000');									
									$.blockUI();

									$.ajax({
										type: 'POST',
										url: BASEURL + '/login/ajax',
										data: { method: 'userLogin',
												username: username,
												password: password
										},
										complete: function( jqXHR, textStatus ) {
											
										},
										success: function( response, textStatus, jqXHRresponse ) {
											if( response.status == 'OK' ) {
												$.pnotify_remove_all();												
												$.pnotify({
													title: 'Authentication Successful',
													text: 'You were successfully logged in. Let\'s Rock!',
													type: 'success',
													icon: 'picon picon-flag-green',
													hide: false,
													width: '400px'
												});
																								
												$('#alerts').hide();
												location.reload();					
											} else {
												$('#dialog-form').dialog('widget').effect('shake');												
												$('#alerts').show();

												$('#username').addClass('ui-state-error');
												$('#password').addClass('ui-state-error');

												$.pnotify_remove_all();
																								
												switch( response.error ) {
													case 'NO_SITE_PERMISSIONS':
														$.pnotify({
															title: 'ERROR',
															text: 'Your account has not been granted any permissions for this site.',
															type: 'error',
															icon: 'picon picon-flag-red',
															hide: false,
															width: '400px'
														});
														
														break;

													case 'NO_SITE_VIEW':
														$.pnotify({
															title: 'ERROR',
															text: 'Your account has not been granted permissions to view this site.',
															type: 'error',
															icon: 'picon picon-flag-red',
															hide: false,
															width: '400px'
														});
														
														break;	

													case 'LOGIN_INVALID_PASSWORD':
													case 'LOGIN_USERNAME_DOES_NOT_EXIST':
														$.pnotify({
															title: 'ERROR',
															text: 'Authentication Failure',
															type: 'error',
															icon: 'picon picon-flag-red',
															hide: false,
															width: '400px'
														});
														
														break;																											
														
													default:
														$.pnotify({
															title: 'ERROR',
															text: 'An unhandled exception has occurred.',
															type: 'error',
															icon: 'picon picon-flag-red',
															hide: false,
															width: '400px'
														});				
												}												
												
												$.unblockUI();
											}
										},
										error: function(  jqXHR, textStatus, errorThrown ) {

										},		
										dataType: 'json'
									});																		
								} else {
									$('#dialog-form').dialog('widget').effect('shake');

									if( !strlen( trim( $('#username').val() ) ) ) {
										$('#username').addClass('ui-state-error');
									}

									if( !strlen( trim( $('#password').val() ) ) ) {
										$('#password').addClass('ui-state-error');
									}
								}
		    		 		}
						},
						open: function(event, ui) { 
							$('.ui-dialog').after('<i id="igBrand" class="icon-camera-retro icon-3x"></i>');
							$('#igBrand').css({'position': 'absolute',
								   			   'top': $('.ui-dialog').offset().top + $('.ui-dialog').height() + 20 + 'px',
								   			   'left': $('.ui-dialog').offset().left + ( $('.ui-dialog').width() / 2 ) +  'px',
									   		   'color': $('.ui-widget-header').css('color'),
									   		   'opacity': '0.4'
							});
							$('.ui-dialog .ui-dialog-title .ui-icon').css({'float': 'left',
								   										   'margin-right': '4px',
								   										   'height': '16px'
							});						
							$('.ui-dialog-titlebar-close').hide();
					    	$('input').blur();
					    	$('input').val('');	

						 	$('#username').bind('keyup paste', function() {
								if( strlen( trim( $(this).val() ) ) ) {
									$(this).removeClass('ui-state-error');
								}
							});

						 	$('#password').unbind('paste keydown');
						 	$('#password').bind('paste keydown', function(event) {
								if( strlen( trim( $(this).val() ) ) ) {
									$(this).removeClass('ui-state-error');
								}

							    if(event.keyCode == 13) {
							    	$('.ui-dialog-buttonset > button').trigger('click');
							    }								
							});
						}						
					});											    
			    }
			        					
		    	$('#theme-switcher').themeswitcher( { 
			    	loadTheme: CURRENT_THEME,
			    	localCssPath: BASEURL + '/css/public/jquery-ui/themes', 
			    	localThemes: SITE_THEMES,
			    	cookieExpires: 315569259747, 
			    	cookiePath: '/',		   
			    	cookieName: 'theme', 
			    	cookieOnSet: function( cookieName, cookieValue ) {
				    	CURRENT_THEME = cookieValue;
				    							    	
				    	if( CURRENT_THEME != 'instagram' ) {							    							    							    									    																					    	
					    	if( !IS_NORMALIZED ) {							    	
				    			$('head').append('<link id="normalizeCss" rel="stylesheet" href="'+BASEURL+'/css/public/normalize.css" type="text/css" />');
				    			IS_NORMALIZED = true;
					    	}

					    	$('instagram').hide();
					    	$('jquery-ui').show();							    								    	
				    	} else {							    	
				    		if( IS_NORMALIZED ) {
					    		$('#normalizeCss').remove();
					    		IS_NORMALIZED = false;			    		
				    		}

				    		$('jquery-ui').hide();						    		
				    		$('instagram').show();
				    	}

			    		$.post( BASEURL, { sessionUpdate: true, theme: cookieValue },
							function( data ) {
				    			if( CURRENT_THEME != 'instagram' ) {									

				    			}																    				
							}
						);					
				    },
			    	onSelect: function() {						  						    
			    					    		   			
		        	},
		        	onSelectComplete: function() {		        	    			        			        			     
			    		$.blockUI({ message: '<img border="0" src="' + BASEURL + '/images/preloader/tools.gif">' });
			    		
		        		$('body').css('background-color', '#ff0000')
		        	    .fadeOut('slow', function () {

		        	    });		        		
		        					    		
			    		window.location.reload();				        		
		        	},
		        	appendThemes: function(switcherpane) {
		        		//$('#themeGalleryList').append('<li style="width: 120px; padding: 2px; margin: 1px; border: 1px solid rgb(17, 17, 17); clear: left; float: left;"><a href="' + BASEURL + '/css/jquery-ui/aristo/aristo.css" style="color: rgb(170, 170, 170); text-decoration: none; float: left; width: 100%; outline: 0pt none;">			<img title="Test" alt="Test" src="http://jqueryui.com/themeroller/images/themeGallery/theme_90_swanky_purse.png" style="float: left; border: 1px solid rgb(51, 51, 51); margin: 0pt 2px;">			<span class="themeName" style="float: left; margin: 3px 0pt;">Test</span>			</a></li>');
				    }
		    	});	    						
		    						    
				$.imgpreload([BASEURL + '/images/preloader/cart/ig_blue_128x128.gif', BASEURL + '/images/icons/demo/paypal_buy_now.png', BASEURL + '/' + DEFAULT_PRELOADER_IMAGE, BASEURL+'/images/preloader/tools.gif', BASEURL+'/images/preloader/download/small/blue.gif', BASEURL + '/images/preloader/spinner/481.gif', BASEURL + '/images/preloader/download/381.gif'], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded
				    }
				});				
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});	
						    
		        $("#id_username").focus();
		        setTimeout(function() {
		            document.getElementById('viewport').setAttribute('content', 'width='+ window.innerWidth + ', user-scalable=no');
		        }, 5);

		        if( LOGIN_ERROR == 1 ) {
		        	$(':input').addClass('error');
		        	$(':input').on('click', function(event) {
						$(this).removeClass('error');
					});		        	
		        }    
		    });
		</script>		
	
	</div> <!-- .root -->

		<?php echo $this->partial( 'partials/footer.phtml' ); ?>
	</body>
</html>